### ISSUE TITLE
ᎠᏕᎭ has extraneous spaces in Immediate forms

### ISSUE THREAD

**Issue by cdrchops** [CherokeeLanguage/cherokeedictionary#78]
ᎠᏕᎭ - Immediate Tense needs to be edited from [ᎯᏗ Ꮟ] to [ᎯᏗᏏ] for syllabary, transliteration, and phonetics. When the “Edit” button is fixed.

https://cherokeedictionary.net/share/100107

**Comment by cwyTommylee** [comment]
Fixed a while ago. Please close.
