### ISSUE TITLE
Add missing /h/ and /ɂ/ to phonetics for ᎠᏍᏆᎵᏍᎦ (breaking sthg long)

### ISSUE THREAD

**Issue by cdrchops** [CherokeeLanguage/cherokeedictionary#84]
Add missing /h/ and /ɂ/ to phonetics for ᎠᏍᏆᎵᏍᎦ (breaking sthg long). Root is -hsgwạli³-.

Also, verify position of rising tone on all forms

**Comment by cwyTommylee** [comment]
Fixed 05/09/2022. Please close.
